name: Trigger Test

on:
  workflow_run:
    workflows: ["build-test.yml"]
    types:
      - completed

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Print a message
        run: echo "Trigger Test workflow was successfully started!"
